name: Trigger auto deployment for event-app-microservice

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/event-app-microservice-AutoDeployTrigger-d682b81c-5e79-4ba9-890f-06c04a726a1c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.EVENTAPPMICROSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EVENTAPPMICROSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EVENTAPPMICROSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.EVENTAPPMICROSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EVENTAPPMICROSERVICE_REGISTRY_PASSWORD }}
          containerAppName: event-app-microservice
          resourceGroup: event_app
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


